<h3> Introduction to Numpy </h3>
In this section we will learn about numpy package that helps in working with arrays.
<h3> References </h3>
Python for Data Analysis, 2nd Edition <br>
<a href="https://docs.scipy.org/doc/numpy-dev/user/quickstart.html"> Numpy Tutorial </a><br>


When you are looking for functionality that is not available in Python core, you can import one of the many Python packages available. Numpy is one of such packages and it helps in working with arrays. 


In [1]:
import numpy as np
a = np.arange(15) # create one dimensional array initialized with values from 0 to 14
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
a = np.arange(15).reshape(3, 5)
print (a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a0 =np.zeros( (3,4) )
a1 = np.ones( (3,4), dtype=int )
print (a0)
print (a1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
np.linspace( 0, 2, 9 ) # 9 members from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [5]:
x = np.linspace( 0, 2*np.pi, 10 ) # create 100 members from 0 to 2*pi
# evaluate sin function at the above generated 100 points
f = np.sin(x)
print (f)

[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [10]:
# select a column (row) of a 2d array
a =  np.random.rand(4,5)
print (a)
# a0 = a[:,0]
# print (a0)
a0 = a[0, :]
print (a0)

[[0.03047497 0.34960113 0.28398705 0.24632928 0.66714697]
 [0.5223047  0.70801264 0.58966767 0.21951565 0.0597901 ]
 [0.06053984 0.10928459 0.85994955 0.40112358 0.14890492]
 [0.25135153 0.5346486  0.09514298 0.98567714 0.937418  ]]
[0.03047497 0.34960113 0.28398705 0.24632928 0.66714697]


#### Indexing arrays

In [11]:
x = np.arange(10)
x[2:5]

array([2, 3, 4])

In [12]:
x[:3]  # access 0 to 3-1

array([0, 1, 2])

In [13]:
x[:-4]  # skip last 4 elements 

array([0, 1, 2, 3, 4, 5])

In [14]:
x[1:7:2] # access starting at 1 with stride 2 upto < 7

array([1, 3, 5])

In [15]:
x[9:4:-2] # access starting at 9 with stride -2  

array([9, 7, 5])

In [16]:
x[::] # implicitly x[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[::-2]  #implicitly x[9:0:-2]

array([9, 7, 5, 3, 1])

In [18]:
y = np.arange(35).reshape(5,7)
print(y)
y[1:5:2,::3]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([[ 7, 10, 13],
       [21, 24, 27]])

Exercise 1: Create a numpy array of size ten: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]. Write a python statement  to reverse the array. Hint: use indexing 

In [4]:
import numpy as np
x=np.linspace(10,100,10)
print(x)
y=x[10::-1]
print(y)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[100.  90.  80.  70.  60.  50.  40.  30.  20.  10.]


Exercise 2: Write Python code to create a 2d array with 1 on the border and 0 inside. Hint: Use indexing

Sample output:
[[ 1. 1. 1. 1. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 0. 0. 0. 1.] 
[ 1. 1. 1. 1. 1.]]

In [9]:
x=np.ones( (5,5), dtype=int )
print(x)
x[1:4,1:4]=0
x

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Exercise 3: Write Python code to create a 2d 8x8 array with alternating 0 and 1 pattern (chess board). Try to use minimum number of lines to code.

Expected output:
                                            
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]

In [15]:
x = np.zeros((8,8),dtype=int)
print(x)
x[1::2,::2]=1
x
x[::2,1::2] = 1
x

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

<h3>Basic Operations on Arrays</h3>

In [ ]:
a = np.array( [20,30,40,50] )
b = np.array([0, 1, 2, 3])
c = a-b
print(c)
c = a**2
print (c)
c = 10*np.sin(a)
print(c)
c = a[a<40]
print (c)
c = a < 35
print (c)

#### Operations on 2D arrays and matrices

In [ ]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
C = A * B
print (C)

In [ ]:
C = A.dot(B)
print (C)

In [ ]:
C = np.dot(A, B)
print (C)

In [ ]:
MA = np.mat(A)
MB = np.mat(B)
MC = MA * MB
print(MC)

#### Working with broadcast and  tile

In [ ]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
print(A+B)

In [ ]:
# before addition B is broadcast as
B = np.array([[1, 2, 3],] * 3)
print(B)

In [ ]:
B = np.array([1, 2, 3])
print(B, B.shape)
T = B[:, np.newaxis]
print (T, T.shape)


In [ ]:
print(A + B[:, np.newaxis])

In [ ]:
# before addition B is broadcast as
np.array([[1, 2, 3],] * 3).transpose()

In [ ]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.tile(np.array([1, 2, 3]), (3, 1))
print(B)

In [ ]:
B = np.tile(np.array([1, 2, 3]), (3, 1))
print(B)

In [ ]:
print(A+B)
print(A*B)

In [ ]:
d1 = np.array([0, 10, 30, 60, 100])
print(np.abs(d1-d1[:, np.newaxis]))

<h3>Linear Algebra</h3>

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print (a)
at = a.transpose()
print(at)
a_inv = np.linalg.inv(a)
print (a_inv)

In [ ]:
y = np.array([[5.], [7.]])
np.dot(a_inv,y)

In [ ]:
y = np.array([[5.], [7.]])
x = np.linalg.solve(a, y)
print (x)

#### Random Functions in Numpy

In [ ]:
# list of 10 random numbers in  [0.0, 1.0)
rnum = np.random.random(10) 
print(rnum)
rnum = rnum/np.sum(rnum)
print(rnum)
print(np.sum(rnum))

In [ ]:
rnum = np.random.random((5,4))
print(rnum)

In [ ]:
print(np.random.randint(1,6))
[ np.random.randint(1, 6) for _ in range(10) ]

In [ ]:
sa = np.array( [20,30,40,50,60,100,300,500,700,800] )
print(np.random.choice(sa))
[ np.random.choice(sa) for _ in range(5) ]

In [ ]:
print(np.random.choice(sa, replace=False))

In [ ]:
np.random.choice(sa,(2,3), replace=False)

In [ ]:
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

Exercise 4: Write a function that is called  with a parameter p, which is a probabilty value between 0 and 1. The function returns a 1 with a probability of p, and zeros with probability of (1-p). Complete the function below.

In [22]:
def random_ones_and_zeros(p):
    """ p: probability 0 <= p <= 1
        returns a 1 with the probability p
    """
    x = np.random.random()
    print(x)
    if x<p:
        return 1,p
    if x>p:
        return 0,1-p
random_ones_and_zeros(0.5)  
    

0.1557326166878048


(1, 0.5)

In [ ]:
A = np.array([[11, 12], [12, 14]])
B = np.array([[0, 1], [2, 3]])
print(A.shape)
C = np.vstack((A,B))
print(C)
print(C.shape)

In [ ]:
C = np.hstack((A,B))
print(C)
print(C.shape)

In [ ]:
a = np.floor(10*np.random.random((2,12)))
a

In [ ]:
x,y,z = np.hsplit(a,3)   # Split a into 3
print(x)
print(y)
print(z)

In [ ]:
x.shape

In [ ]:
x,y,z = np.hsplit(a,(3,4))   # Split a after the third and the fourth column
print(x)
print(y)
print(z)

In [ ]:
x,y = np.vsplit(a,2)
print(x)
print(y)

In [ ]:
# Boolean Mask
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,7,2,8,6,9,5])
R = C[A<=5]
print(R)

In [ ]:
# indexing with an integer array
C[[0, 2, 3, 1, 4, 1]]

Exercise 5: Extract from the array np.array([3,4,6,10,24,89,45,43,46,99,100]) with Boolean masking all the number

which are not divisible by 3

which are divisible by 5

which are divisible by 3 and 5

which are divisible by 3 and set them to 42

In [23]:
x=np.array([3,4,6,10,24,89,45,43,46,99,100])
print(x)

[  3   4   6  10  24  89  45  43  46  99 100]


In [27]:
y=x[x%3==0]
print(y)
z=x[x%5==0]
print(z)
c=x[(x%3==0) & (x%5==0)]
print(c)
x[x%3==0]=42
print(x)

[ 3  6 24 45 99]
[ 10  45 100]
[45]
[ 42   4  42  10  42  89  42  43  46  42 100]
